# Copyright 2025 The HuggingFace Team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Adapted from huggingface/transformers: https://github.com/huggingface/transformers/blob/21a2d900eceeded7be9edc445b56877b95eda4ca/setup.py


import re
import shutil
import os
from pathlib import Path

from setuptools import find_packages, setup

# If a ROCm-built torch is already installed, avoid letting pip silently replace it.
# IMPORTANT: Do NOT hard-fail during metadata generation/build steps, otherwise
# `pip install -e . --no-deps` and other build-frontend operations will fail.
try:
    _allow_replace = os.environ.get("OPENR1_ALLOW_TORCH_REPLACE", "0") == "1"
    _skip_guard = os.environ.get("OPENR1_SKIP_TORCH_GUARD", "0") == "1"

    if not _skip_guard:
        import importlib.util

        torch_spec = importlib.util.find_spec("torch")
        if torch_spec is not None:
            import torch as _torch_inst

            _is_rocm_torch = hasattr(_torch_inst.version, "hip") and _torch_inst.version.hip is not None
            if _is_rocm_torch and not _allow_replace:
                # Only warn. Editable installs with --no-deps should still work.
                print(
                    "\n[open-r1] Detected ROCm-built PyTorch in this environment. "
                    "To avoid pip replacing it, ALWAYS install this project with --no-deps (recommended):\n"
                    "  pip install -e . --no-deps\n"
                    "If you really want pip to replace torch, set OPENR1_ALLOW_TORCH_REPLACE=1.\n"
                )
except Exception:
    # Best-effort guard; never break installation due to probing issues.
    pass

# ROCm/DTK environment guidance: detect common DTK/ROCm install paths and print clear instructions
# to users who try to `pip install -e .` on a ROCm machine with an incompatible CUDA torch wheel.
try:
    _rocm_hint_paths = ["/opt/rocm", "/opt/dtk", "/opt/dtk-25.04.2"]
    _rocm_present = any(Path(p).exists() for p in _rocm_hint_paths) or bool(Path("/opt/dtk").exists()) or bool(Path("/opt/rocm").exists())
    if _rocm_present:
        # Provide a concise, actionable hint. We avoid network lookups during setup.
        print("\n*** DETECTED ROCm/DTK RUNTIME ON HOST ***")
        print("It looks like this machine has ROCm/DTK libraries installed (e.g., /opt/dtk or /opt/rocm).\n"
              "To avoid native crashes, DO NOT install CUDA-built PyTorch wheels on ROCm nodes.\n"
              "Recommended quick steps:\n"
              "  1) Uninstall any existing CUDA torch: pip uninstall -y torch torchvision torchaudio\n"
              "  2) Install a ROCm-matching wheel. Example (adjust rocmX.Y and torch version to match your DTK):\n"
              "       pip install --index-url https://download.pytorch.org/whl/rocm5.6 \\\n"
              "           torch==2.2.2+rocm5.6 torchvision --extra-index-url https://download.pytorch.org/whl/rocm5.6\n"
              "     (If rocm5.6 wheels are not suitable for your DTK, ask your admin or check https://download.pytorch.org/whl/)\n"
              "  3) After installing ROCm PyTorch, reinstall this project: pip install -e .\n"
              "If you cannot install ROCm wheels via pip, ask your cluster admin for the recommended wheel/module.\n")
except Exception:
    # Non-fatal: avoid failing setup due to our hint logic
    pass

# Remove stale open_r1.egg-info directory to avoid https://github.com/pypa/pip/issues/5466
stale_egg_info = Path(__file__).parent / "open_r1.egg-info"
if stale_egg_info.exists():
    print(
        (
            "Warning: {} exists.\n\n"
            "If you recently updated open_r1, this is expected,\n"
            "but it may prevent open_r1 from installing in editable mode.\n\n"
            "This directory is automatically generated by Python's packaging tools.\n"
            "I will remove it now.\n\n"
            "See https://github.com/pypa/pip/issues/5466 for details.\n"
        ).format(stale_egg_info)
    )
    shutil.rmtree(stale_egg_info)


# IMPORTANT: all dependencies should be listed here with their version requirements, if any.
#   * If a dependency is fast-moving (e.g. trl), pin to the exact version
_deps = [
    # Keep installer lightweight; ROCm/Qwen3.5 runtime is managed manually in the venv.
    "accelerate>=1.4.0",
    "numpy<2.0.0",
    "datasets>=3.2.0",
    "einops>=0.8.0",
    "hf_transfer>=0.1.4",
    "huggingface-hub[cli,hf_xet]>=0.31.0,<2.0",
    "langdetect",
    "latex2sympy2_extended>=1.0.6",
    "liger-kernel>=0.5.10",
    "math-verify==0.5.2",
    "packaging>=23.0",
    "peft>=0.14.0",
    "safetensors>=0.3.3",
    "sentencepiece>=0.1.99",
    "wandb>=0.19.1",
    "async-lru>=2.0.5",
    "aiofiles>=24.1.0",
    "pandas>=2.2.3",
    # Center versions around transformers 5.2.0; install in the environment if you use training scripts.
    "transformers==5.2.0",
    # Keep transformers/trl out of install_requires for ROCm/Qwen3.5; install them explicitly in the venv.
    "pytest",
    "parameterized>=0.9.0",
    "ruff>=0.9.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "e2b-code-interpreter>=1.0.5",
    "python-dotenv",
    "morphcloud==0.1.67",
    "jieba",
    "lighteval @ git+https://github.com/huggingface/lighteval.git@d3da6b9bbf38104c8b5e1acc86f83541f9a502d1",
    "deepspeed==0.16.8",
]

# Build a mapping from short package key -> full spec in a simple, robust way.
# Avoids a single complex regex to silence lint warnings and improves readability.
deps = {}
for full_spec in _deps:
    # Extract package name up to the first special char (one of ' ', '[', '!', '=', '<', '>', '~')
    m = re.match(r"^([^\s\[!=<>~]+)", full_spec)
    if m:
        pkg = m.group(1)
    else:
        # Fallback: use the entire spec as key (shouldn't normally happen)
        pkg = full_spec
    deps[pkg] = full_spec


def deps_list(*pkgs):
    out = []
    missing = []
    for pkg in pkgs:
        spec = deps.get(pkg)
        if spec is None:
            missing.append(pkg)
            continue
        out.append(spec)
    if missing:
        print(
            "[open-r1] Warning: extras reference missing dependency keys: "
            + ", ".join(missing)
            + ". They will be skipped."
        )
    return out


extras = {}
extras["tests"] = deps_list("pytest", "parameterized", "math-verify", "jieba")
# removed extras['torch'] because torch is now provided as an optional extra (see below)
extras["quality"] = deps_list("ruff", "isort", "flake8")
extras["code"] = deps_list("e2b-code-interpreter", "python-dotenv", "morphcloud", "jieba", "pandas", "aiofiles")
extras["eval"] = deps_list("lighteval", "math-verify")
extras["dev"] = extras["quality"] + extras["tests"] + extras["eval"] + extras["code"]

# Optional extras for different device stacks.
# Note: ROCm users should install the matching ROCm PyTorch wheel first (pip from the PyTorch ROCm index)
# and then `pip install .[rocm]`. bitsandbytes is CUDA-only in most published builds, so it's provided
# behind the 'cuda' and 'bnb' extras only.
extras["cuda"] = [
    "torch>=2.6.0,<3.0",
    "bitsandbytes>=0.43.0",
]
# ROCm users: This extra is intentionally left empty to avoid pip auto-installing non-ROCm torch wheels.
# Please install the correct ROCm PyTorch wheel manually before using this extra.
extras["rocm"] = [
]
extras["bnb"] = [
    "bitsandbytes>=0.43.0",
]
# Move deepspeed to an optional extra to avoid pulling heavy binaries for users who don't need it.
extras["deepspeed"] = [deps["deepspeed"]]
# Aggregate common full set
extras["full"] = list({
    *extras.get("dev", []),
    *extras.get("cuda", []),
    *extras.get("rocm", []),
    *extras.get("bnb", []),
    *extras.get("deepspeed", []),
})

# core dependencies shared across the whole project - keep this to a bare minimum :)
install_requires = [
    deps["accelerate"],
    deps["numpy"],
    deps["einops"],
    deps["datasets"],
    deps["hf_transfer"],
    deps["huggingface-hub"],
    deps["langdetect"],
    deps["latex2sympy2_extended"],
    deps["math-verify"],
    deps["liger-kernel"],
    deps["packaging"],
    deps["safetensors"],
    deps["sentencepiece"],
    deps["wandb"],
    deps["async-lru"],
    deps["pandas"],
    # Core training scripts depend on transformers; pin to the requested version.
    deps["transformers"],
]

setup(
    name="open-r1",
    version="0.1.0.dev0",  # expected format is one of x.y.z.dev0, or x.y.z.rc1 or x.y.z (no to dashes, yes to dots)
    author="The Hugging Face team (past and future)",
    author_email="lewis@huggingface.co",
    description="Open R1",
    long_description=open("README.md", "r", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    keywords="llm inference-time compute reasoning",
    license="Apache",
    url="https://github.com/huggingface/open-r1",
    package_dir={"": "src"},
    packages=find_packages("src"),
    zip_safe=False,
    extras_require=extras,
    python_requires=">=3.10.9",
    install_requires=install_requires,
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Education",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)